config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'events#index'

  resources :events do
    collection do
      resource :export, only: %i[create], module: :events
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :event_type
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :event_type_id
    validates :user
    validates :date
    validates :start_at
    validates :finish_at
  end

  validate :event_date
  validate :event_intersection

  scope :chronologically, -> { order(date: :asc, start_at: :asc) }

  private

  def event_date
    errors.add(:past_date, 'cannot be in the past') unless date&.future?
  end

  def event_intersection
    return if Event.where(user_id: user_id, date: date).where.not(id: id).none?

    errors.add(:intersection, 'cannot intersects, another event this date')
  end
end

app/models/event_type.rb
class EventType < ApplicationRecord
  has_many :events, dependent: :restrict_with_error

  validates :title, presence: true, uniqueness: { case_sensitive: false }

  scope :evrone_special, -> { where(title: ['Внутренний митап', 'Прогон доклада']) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :restrict_with_error
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/events/exports_controller.rb
class Events::ExportsController < ApplicationController
  def create
    send_data Events::Export.new.call, filename: filename
  end

  private

  def filename
    'events-export.csv'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_current_user_event, only: %i[edit update]

  def index
    @events = Event.includes(:user).chronologically.page(page)
  end

  def show
    @event = Event.find(params[:id])

    # TODO make it in a single PORO
    render layout: 'evrone' if @event.event_type_id.in?(EventType.evrone_special.pluck(:id))
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params.merge(user_id: current_user.id))

    if @event.valid?
      redirect_to events_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to events_path
    else
      render :new
    end
  end

  private

  def find_current_user_event
    @event ||= Event.find_by!(id: params[:id], user_id: current_user.id)
  end

  def page
    params[:page] || 0
  end

  def event_params
    params.require(:event).permit(:title, :event_type_id, :date, :start_at, :finish_at, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def allowed_to_event?(event)
    current_user.id == event.user_id
  end

  def all_tz
    ActiveSupport::TimeZone.all
  end
end

app/views/events/_event.html.haml
%tr
  %td
    %span.oi.oi-move.sort-icon
  %td= event.title
  %td= event.author
  %td= event.date
  %td= event.duration
  %td
    %a.text-nowrap.btn.btn-secondary.btn-sm{href: event_path(event.id), role: "button"}
      %span.oi.oi-eye
      = t("Show")
    - if allowed_to_event?(event)
      %a.text-nowrap.btn.btn-primary.btn-sm{href: edit_event_path(event.id), role: "button"}
        %span.oi.oi-pencil
        = t("edit")

app/views/events/_form.html.haml
- if @event.errors.any?
  .error_explanation
    %h2= "#{pluralize(@event.errors.count, 'error')} prohibited this article from being saved:"
    %ul
      - @event.errors.full_messages.each do |msg|
        %li.danger= msg

.row
  .col-lg-9
    = simple_form_for @event do |f|
      .form-group.string.optional.category_text.form-group-valid
        = f.input :title
        = f.association :event_type, include_blank: false
        = f.input :date
        = f.input :start_at
        = f.input :finish_at
        = f.input :description

      = f.submit 'ok', { class: 'btn btn-success' }

app/views/events/edit.html.haml
%nav{'aria-label' => 'breadcrumb'}
  %ol.breadcrumb
    %li.breadcrumb-item
      %a{href: events_path}
        = t('title')

%h1= t('events.edit')

= render 'form'

app/views/events/index.html.haml
.clearfix
  .float-sm-right
    %a.btn.btn-success{href: new_event_path, role: "button"}
      %span.oi.oi-plus
      = t("new")

  = button_to 'Export to CSV', export_path, method: :post, class: 'btn btn-danger'

  %h2= t("Events")

%hr

.row
  .col-lg-10
    .table-responsive
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th.border-top-0
            %th.border-top-0= t("title")
            %th.border-top-0= t("author")
            %th.border-top-0= t("event date")
            %th.border-top-0= t("duration hours")
            %th.border-top-0
        %tbody
          - if @events.any?
            -# = render @events
            - @events.each do |event|
              = render partial: 'event', locals: { event: EventPresenter.new(event) }
    = paginate @events

app/views/events/new.html.haml
%nav{'aria-label' => 'breadcrumb'}
  %ol.breadcrumb
    %li.breadcrumb-item
      %a{href: events_path}
        = t('title')

%h1= t('events.new')

= render 'form'

app/views/events/show.html.haml
%nav{'aria-label' => 'breadcrumb'}
  %ol.breadcrumb
    %li.breadcrumb-item
      %a{href: events_path}
        = t('title')

%h1= t('events.edit')

.form-group.string.optional.category_text.form-group-valid
  = @event.title
  %br
  = @event.event_type.title
  %br
  = @event.date
  %br
  = @event.start_at
  %br
  = @event.finish_at
  %br
  = @event.description

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChallengeMiddlePlus
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .navbar.navbar-expand-lg.navbar-dark.bg-dark.navbar-mb-10
      - if current_user
        = button_to 'sign_out', destroy_user_session_path, method: :delete, class: 'btn btn-light'

    .container

      = yield

app/views/layouts/evrone.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChallengeMiddlePlus
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .navbar.navbar-expand-lg.navbar-dark.bg-dark.navbar-mb-10
      - if current_user
        = button_to 'sign_out', destroy_user_session_path, method: :delete, class: 'btn btn-light'
      = image_tag('evrone.jpg', width: '50px')

    .container
      = yield